[17.12.2024 17:48:43,21] Running enslige_mindreårige.py 
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
X_FUNCTIONS_KEY loaded successfully.
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
GITHUB_TOKEN loaded successfully.
Fylker CSV data loaded successfully.
Kommuner CSV data loaded successfully.

New data detected. Checking last 200 rows for specific changes...


Debug information:
Numeric columns detected: Index(['anmodning om bosetting', 'faktisk bosetting'], dtype='object', name='Kategori')
Key columns detected: ['�r']

Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Bosetting_av_flyktninger\enslige_mindre�rige.py", line 220, in <module>
    is_new_data = compare_to_github(df_telemark, file_name, github_folder, temp_folder)
  File "D:\Scripts\analyse\Telemark\Python\Helper_scripts\github_functions.py", line 222, in compare_to_github
    comparison = last_200_new.merge(
  File "C:\Users\_eve1509\AppData\Local\anaconda3\envs\analyse\lib\site-packages\pandas\core\frame.py", line 9843, in merge
    return merge(
  File "C:\Users\_eve1509\AppData\Local\anaconda3\envs\analyse\lib\site-packages\pandas\core\reshape\merge.py", line 148, in merge
    op = _MergeOperation(
  File "C:\Users\_eve1509\AppData\Local\anaconda3\envs\analyse\lib\site-packages\pandas\core\reshape\merge.py", line 741, in __init__
    self._maybe_coerce_merge_keys()
  File "C:\Users\_eve1509\AppData\Local\anaconda3\envs\analyse\lib\site-packages\pandas\core\reshape\merge.py", line 1405, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on datetime64[ns] and object columns. If you wish to proceed you should use pd.concat
[17.12.2024 17:48:46,00] Script failed with error code 1 
