Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
X_FUNCTIONS_KEY loaded successfully.
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
GITHUB_TOKEN loaded successfully.
An error occurred: HTTPSConnectionPool(host='www.norskeutslipp.no', port=443): Max retries exceeded with url: /no/Komponenter/Utslipp/Klimagasser-CO2-ekvivalenter/?ComponentType=utslipp&ComponentPageID=1166&SectorID=600 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018B256A8A90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
Email notifications disabled. Errors in Extract_NorskeUtslipp_Data were not sent.


Errors:
Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries/04_Klima_og_energi/Klimagassutslipp/norskeutslipp.py", line 80, in <module>
    df = df_downloaded.copy()
NameError: name 'df_downloaded' is not defined

ERROR conda.cli.main_run:execute(125): `conda run python D:\Scripts\analyse\Telemark\Python\Queries/04_Klima_og_energi/Klimagassutslipp/norskeutslipp.py` failed. (See above for error)
